# Generated by Django 4.2.1 on 2023-06-09 12:45

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_configuration_scrapy_job_keywords"),
    ]

    operations = [UnaccentExtension(), TrigramExtension()]
