# Generated by Django 4.1.1 on 2022-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
    ]
