# Generated by Django 4.1.1 on 2022-10-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="companies.industry",
                verbose_name="Industry",
            ),
        ),
    ]
