# Generated by Django 4.2.1 on 2023-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, unique=True, verbose_name="Sort order"
            ),
        ),
    ]
