# Generated by Django 4.1.1 on 2022-09-20 13:17

from django.db import migrations

from talent.jobs.utils import Attendances
from talent.jobs.utils import ContractTypes
from talent.jobs.utils import Temporalities


def fill_temporalities(apps, schema_editor):
    Temporality = apps.get_model("jobs", "Temporality")

    for temporality in Temporalities:
        Temporality.objects.create(name=temporality.value)


def fill_attendances(apps, schema_editor):
    Attendance = apps.get_model("jobs", "Attendance")

    for attendance in Attendances:
        Attendance.objects.create(name=attendance.value)


def fill_contract_types(apps, schema_editor):
    ContractType = apps.get_model("jobs", "ContractType")

    for contract_type in ContractTypes:
        ContractType.objects.create(name=contract_type.value)


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_temporalities),
        migrations.RunPython(fill_attendances),
        migrations.RunPython(fill_contract_types),
    ]
