# Generated by Django 4.1.1 on 2022-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="experiencelevel",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="experiencelevel",
            name="years",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Years"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="temporality",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
    ]
