# Generated by Django 4.1.1 on 2022-10-10 12:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, verbose_name="Name slug"),
        ),
    ]
