# Generated by Django 4.2.1 on 2023-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_location_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["name"], name="jobs_locati_name_5d810a_idx"),
        ),
    ]
