# Generated by Django 4.2.1 on 2023-06-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_location_jobs_locati_name_5d810a_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="parent",
        ),
    ]
