# Generated by Django 4.2.1 on 2023-06-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("jobs", "0008_remove_location_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.city",
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
                verbose_name="Region",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.subregion",
                verbose_name="SubRegion",
            ),
        ),
    ]
