# Generated by Django 4.1.1 on 2022-09-20 13:36

from django.db import migrations

INITIAL_SOURCES = ["Linkedin", "Indeed", "Infoempleo", "Infojobs"]


def fill_sources(apps, schema_editor):
    Source = apps.get_model("offers", "Source")

    for source_name in INITIAL_SOURCES:
        Source.objects.create(name=source_name)


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [migrations.RunPython(fill_sources)]
