# Generated by Django 4.1.1 on 2022-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.TextField(unique=True, verbose_name="Name"),
        ),
    ]
