# Generated by Django 4.1.1 on 2022-10-06 11:19

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job"),
        ("offers", "0003_alter_source_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="title",
        ),
        migrations.AddField(
            model_name="offer",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="jobs.job",
                verbose_name="Job title",
            ),
        ),
    ]
