# Generated by Django 4.1.1 on 2022-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_remove_offer_title_offer_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="url",
            field=models.URLField(max_length=2048, verbose_name="URL"),
        ),
    ]
