# Generated by Django 4.1.1 on 2022-10-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0005_alter_offer_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="URL"
            ),
        ),
    ]
