# Generated by Django 4.1.1 on 2022-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0006_alter_recruiter_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="offer_id",
            field=models.TextField(unique=True, verbose_name="Offer ID"),
        ),
    ]
