# Generated by Django 4.1.1 on 2022-11-17 13:49

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import talent.offers.model_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_location_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0009_alter_offer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferDuplicate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(blank=True, default=True, verbose_name="Is active?"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Extra data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last modification date"),
                ),
                ("from_offer_id", models.UUIDField(verbose_name="From offer ID")),
                ("to_offer_id", models.UUIDField(verbose_name="To offer ID")),
                (
                    "job_title_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Job title similarity (1-100)",
                    ),
                ),
                (
                    "description_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Description similarity (1-100)",
                    ),
                ),
                (
                    "location_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Location similarity (1-100)",
                    ),
                ),
                (
                    "temporality_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temporality similarity (1-100)",
                    ),
                ),
                (
                    "attendance_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Attendance similarity (1-100)",
                    ),
                ),
                (
                    "contract_type_similarity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Contract type similarity (1-100)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer duplicate",
                "verbose_name_plural": "Offer duplicates",
            },
        ),
        migrations.CreateModel(
            name="OfferAiInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(blank=True, default=True, verbose_name="Is active?"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Extra data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last modification date"),
                ),
                ("job_title", models.TextField(verbose_name="Job title (translated)")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description (translated)"),
                ),
                (
                    "basic_taxonomy",
                    models.TextField(blank=True, null=True, verbose_name="Basic taxonomy"),
                ),
                (
                    "advanced_taxonomy",
                    models.TextField(blank=True, null=True, verbose_name="Advanced taxonomy"),
                ),
                (
                    "salary",
                    models.JSONField(
                        blank=True,
                        default=talent.offers.model_utils.get_default_salary_json,
                        null=True,
                        verbose_name="Salary (AI)",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_matchings",
                        to="jobs.attendance",
                        verbose_name="Attendance (AI)",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_matchings",
                        to="jobs.contracttype",
                        verbose_name="Contract type (AI)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching",
                        to="offers.offer",
                        verbose_name="Offer",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offer_matchings",
                        to="jobs.skill",
                        verbose_name="Skills (AI)",
                    ),
                ),
                (
                    "temporality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_matchings",
                        to="jobs.temporality",
                        verbose_name="Temporality (AI)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer AI info",
                "verbose_name_plural": "Offers AI info",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="duplicates",
            field=models.ManyToManyField(
                blank=True,
                through="offers.OfferDuplicate",
                to="offers.offer",
                verbose_name="Duplicates",
            ),
        ),
    ]
