# Generated by Django 4.1.1 on 2022-11-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_location_slug"),
        ("offers", "0010_offerduplicate_offeraiinfo_alter_offer_duplicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeraiinfo",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers_ai",
                to="jobs.location",
                verbose_name="Location (AI)",
            ),
        ),
        migrations.AlterField(
            model_name="offeraiinfo",
            name="attendance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers_ai",
                to="jobs.attendance",
                verbose_name="Attendance (AI)",
            ),
        ),
        migrations.AlterField(
            model_name="offeraiinfo",
            name="contract_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers_ai",
                to="jobs.contracttype",
                verbose_name="Contract type (AI)",
            ),
        ),
        migrations.AlterField(
            model_name="offeraiinfo",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers_ai",
                to="jobs.skill",
                verbose_name="Skills (AI)",
            ),
        ),
        migrations.AlterField(
            model_name="offeraiinfo",
            name="temporality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers_ai",
                to="jobs.temporality",
                verbose_name="Temporality (AI)",
            ),
        ),
    ]
