# Generated by Django 4.1.1 on 2022-11-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0011_offeraiinfo_location_alter_offeraiinfo_attendance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerduplicate",
            name="from_offer_id",
        ),
        migrations.RemoveField(
            model_name="offerduplicate",
            name="to_offer_id",
        ),
        migrations.AddField(
            model_name="offerduplicate",
            name="from_offer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicates_from",
                to="offers.offer",
                verbose_name="From offer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offerduplicate",
            name="to_offer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicates_to",
                to="offers.offer",
                verbose_name="To offer",
            ),
            preserve_default=False,
        ),
    ]
