# Generated by Django 4.1.1 on 2022-11-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0012_remove_offerduplicate_from_offer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeraiinfo",
            name="offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_info",
                to="offers.offer",
                verbose_name="Offer",
            ),
        ),
    ]
