# Generated by Django 4.1.1 on 2022-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0013_alter_offeraiinfo_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeraiinfo",
            name="job_title_slug",
            field=models.SlugField(
                blank=True, max_length=256, verbose_name="Job title slug"
            ),
        ),
    ]
