# Generated by Django 4.2.1 on 2023-05-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0014_offeraiinfo_job_title_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ("company__sort_order", "-posting_date"),
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
