# Generated by Django 4.2.1 on 2023-05-23 19:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0015_alter_offer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="description_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description_search_vector"],
                name="offers_offe_descrip_2e9c91_gin",
            ),
        ),
    ]
